version: '2'
services:
  task_mgmt:
    build: .
    volumes:
      - .:/go/src/github.com/datatogether/task_mgmt
      - ./sql:/sql
    ports:
     - 8080:8080
    networks:
      - back-tier
    depends_on:
      - ipfs
      - rabbitmq
      - postgres
    environment:
      - PORT=8080
      - TLS=false
      - GOLANG_ENV=develop
      - POSTGRES_DB_URL=postgres://postgres@postgres/postgres?sslmode=disable
      - PUBLIC_KEY=nothing_yet
      - POSTMARK_KEY=POSTMARK_API_TEST
      - EMAIL_NOTIFICATION_RECIPIENTS=brendan@qri.io
      - GITHUB_LOGIN_URL=http://localhost:3100/oauth/github
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/
      - IPFS_API_URL=http://ipfs:5001/api/v0
      - REDIS_URL=redis://redis:6379
      - RPC_PORT=4400
  ipfs:
    image: "ipfs/go-ipfs:latest"
    networks:
      - back-tier
    ports:
      - 5001:5001
  rabbitmq:
    image: "library/rabbitmq:latest"
    networks:
      - back-tier
    ports:
      - 5672:5672
  redis:
    image: "library/redis:alpine"
    networks:
      - back-tier
    ports:
      - 6379:6379
  postgres:
    image: "postgres:9.6-alpine"
    networks:
      - back-tier

networks:
  back-tier: